package com.tmb.enums;

public enum ConfigProperties {

	URL,
	OVERRIDEREPORTS,
	PASSEDSTEPSCREENSHOTS,
	FAILEDSTEPSCREENSHOTS,
	SKIPPEDSTEPSCREENSHOTS,
	RETRYFAILEDTESTS,
	RUNMODE,
	REMOTEDRIVERURL;
}
